services:
  prefect-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prefect-server:
    image: prefecthq/prefect:3-python3.13
    restart: always
    command: prefect server start
    ports:
      - "4200:4200"
    depends_on:
      - prefect-db
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_SERVER_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@prefect-db:5432/prefect

  worker:
    image: prefecthq/prefect:3-python3.13
    command: prefect worker start --pool default-agent-pool
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    depends_on:
      prefect-server:
        condition: service_started

  flow:
    image: prefecthq/prefect:3-python3.13
    working_dir: /app
    command: tail -f /dev/null
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
      PREFECT_LOCAL_STORAGE_PATH: /flow-storage
      PYTHONPATH: /app
    depends_on:
      prefect-server:
        condition: service_started
    volumes:
      - flow-storage:/flow-storage
      - ./:/app

  api:
    restart: always
    image: prefecthq/prefect:3.3.3-python3.13
    command: uv run -m main
    ports:
      - "8000:8000"
    depends_on:
      flow:
        condition: service_started
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
      PREFECT_LOCAL_STORAGE_PATH: /flow-storage
      PYTHONPATH: /app
    volumes:
      - flow-storage:/flow-storage
      - ./:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
      - ./data/brazilian-e-commerce:/data/brazilian-e-commerce
volumes:
  flow-storage:
  postgres_data:
  db-data: